language: php
php:
  - 5.5
  - 5.6
#  - hhvm
#  - nightly
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution

install:
  - composer require "neos/neos-development-collection dev-master" "neos/flow-development-collection dev-master"
  - rm -rf Packages/Neos
  - mv ../neos-development-collection Packages/Neos
before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
