language: php
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql BEHAT=true
#    - php: 5.6
#      env: DB=pgsql
    - php: 5.5
      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b 1.2
  - cd neos-development-distribution
install:
  - composer install
  - rm -rf Packages/Neos
  - mv ../neos-development-collection Packages/Neos
before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - if [ "$BEHAT" = "true" ]; then composer install -d Build/Behat; fi
script:
  - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Neos tests"
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -v -c Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/behat.yml.dist; fi
