language: php
matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql
#    - php: 5.6
#      env: DB=pgsql
    - php: 5.5
      env: DB=sqlite
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b 1.2
  - cd neos-development-distribution
install:
  - composer install
  - rm -rf Packages/Neos
  - mv ../neos-development-collection Packages/Neos
before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - FLOW_CONTEXT=Testing ./flow configuration:show --type Settings --path TYPO3.Flow.persistence.backendOptions
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Neos tests"
