TYPO3:
  Media:
    bodyClasses: 'media-browser'
    scripts:
      - resource://TYPO3.Twitter.Bootstrap/Public/Libraries/jQuery/jquery-1.8.2.min.js
      - resource://TYPO3.Twitter.Bootstrap/Public/2/js/bootstrap.min.js
    styles:
      - resource://TYPO3.Twitter.Bootstrap/Public/2/css/bootstrap.min.css
      - resource://TYPO3.Media/Public/Libraries/plupload/jquery.plupload.queue/css/jquery.plupload.queue.css
      - resource://TYPO3.Media/Public/Styles/Main.css